'''Reusable ground-estimation and lower-envelope public entries.'''

from hjlib_ground_solver.estimate_ground.by_mesh_lower_envelope import (
    Mesh_Lower_Envelope_Candidate,
    Mesh_Lower_Envelope_Summary,
    compute_per_frame_mesh_minimum_height,
    summarize_mesh_lower_envelope,
)
from hjlib_ground_solver.estimate_ground.by_hj_derived_plantar_zmin import (
    HJ_Derived_Plantar_ZMin_Ground_Provenance,
    HJ_Derived_Plantar_ZMin_Ground_Result,
    HJ_Derived_Plantar_ZMin_Ground_Side,
    estimate_hj_derived_plantar_zmin_ground,
)
from hjlib_ground_solver.estimate_ground.by_mesh_lower_envelope_peeling import (
    Mesh_Lower_Envelope_Peel_Proposal,
    Mesh_Lower_Envelope_Peeling_Config,
    Mesh_Lower_Envelope_Peeling_Result,
    Mesh_Lower_Envelope_Peeling_Status,
    peel_separated_mesh_lower_envelope_prefixes,
)
from hjlib_ground_solver.estimate_ground.by_static_foot_humor import (
    Static_Foot_HuMoR_Cluster,
    Static_Foot_HuMoR_Config,
    Static_Foot_HuMoR_Result,
    Static_Foot_HuMoR_Sample,
    Static_Foot_HuMoR_Status,
    estimate_static_foot_humor_baseline,
)
from hjlib_ground_solver.estimate_ground.by_static_foot_plantar_humor import (
    Static_Foot_Plantar_HuMoR_Cluster,
    Static_Foot_Plantar_HuMoR_Config,
    Static_Foot_Plantar_HuMoR_Result,
    Static_Foot_Plantar_HuMoR_Sample,
    Static_Foot_Plantar_HuMoR_Status,
    estimate_static_foot_plantar_humor_baseline,
)
from hjlib_ground_solver.estimate_ground.by_vertex_subset_observation import (
    Vertex_Subset_Observation_Chunk,
    compute_vertex_subset_observation_chunk,
)
from hjlib_ground_solver.estimate_ground.observation_density import (
    Ground_Observation_Density,
    Ground_Observation_KDE_Density,
    compute_ground_observation_density,
    compute_ground_observation_kde_density,
)
from hjlib_ground_solver.estimate_ground.by_vanishing_direction import (
    Vertical_VP_Selection_Ground_Normal_Result,
    Vanishing_Direction_Ground_Normal_Result,
    solve_ground_normal_by_vertical_vp_selection,
    solve_ground_normal_from_vanishing_directions,
)
from hjlib_ground_solver.estimate_ground.by_orthogonal_vanishing_direction import (
    Orthogonal_Consensus_Ground_Normal_Result,
    solve_ground_normal_by_orthogonal_consensus,
    solve_ground_normal_by_role_aware_orthogonal_consensus,
)
from hjlib_ground_solver.estimate_ground.by_person_vertical_lines import (
    Person_Vertical_Direction_Evidence_Result,
    fit_person_vertical_direction_evidence,
)
from hjlib_ground_solver.estimate_ground.by_equal_vertical_lines import (
    Equal_Weight_Vertical_Line_Ground_Normal_Result,
    Source_Weighted_Vertical_Line_Ground_Normal_Result,
    solve_ground_normal_by_equal_weight_vertical_lines,
    solve_ground_normal_by_source_weighted_vertical_lines,
)
# Temporarily deprecated V1 exports retained for historical compatibility.
from hjlib_ground_solver.estimate_ground.person_ankle_plane import (
    Person_Ankle_Foot_Shape,
    Person_Ankle_Foot_Side,
    Person_Ankle_Global_Config,
    Person_Ankle_Height_Hypothesis,
    Person_Ankle_Height_Shape,
    Person_Ankle_Hypothesis_Segment,
    Person_Ankle_Local_Cluster,
    Person_Ankle_Local_Config,
    Person_Ankle_Noise_Reason,
    Person_Ankle_Observation_Table,
    Person_Ankle_Plane_Config,
    Person_Ankle_Plane_Input,
    Person_Ankle_Plane_Result,
    Person_Ankle_Plane_Status,
    Person_Ankle_Recurrence_Episode,
    Person_Ankle_Run,
    Person_Ankle_Run_Provenance,
    Person_Ankle_Source_Plane,
    Person_Ankle_Space_Shape,
    Person_Ankle_Time_Shape,
    Person_Ankle_Transition_Check,
    Person_Ankle_Transition_Config,
    Person_Ankle_Transition_Outcome,
    infer_person_ankle_plane_distribution,
)


__all__ = [
    'HJ_Derived_Plantar_ZMin_Ground_Provenance',
    'HJ_Derived_Plantar_ZMin_Ground_Result',
    'HJ_Derived_Plantar_ZMin_Ground_Side',
    'estimate_hj_derived_plantar_zmin_ground',
    'Mesh_Lower_Envelope_Candidate',
    'Mesh_Lower_Envelope_Summary',
    'compute_per_frame_mesh_minimum_height',
    'summarize_mesh_lower_envelope',
    'Mesh_Lower_Envelope_Peel_Proposal',
    'Mesh_Lower_Envelope_Peeling_Config',
    'Mesh_Lower_Envelope_Peeling_Result',
    'Mesh_Lower_Envelope_Peeling_Status',
    'peel_separated_mesh_lower_envelope_prefixes',
    'Static_Foot_HuMoR_Cluster',
    'Static_Foot_HuMoR_Config',
    'Static_Foot_HuMoR_Result',
    'Static_Foot_HuMoR_Sample',
    'Static_Foot_HuMoR_Status',
    'estimate_static_foot_humor_baseline',
    'Static_Foot_Plantar_HuMoR_Cluster',
    'Static_Foot_Plantar_HuMoR_Config',
    'Static_Foot_Plantar_HuMoR_Result',
    'Static_Foot_Plantar_HuMoR_Sample',
    'Static_Foot_Plantar_HuMoR_Status',
    'estimate_static_foot_plantar_humor_baseline',
    'Vertex_Subset_Observation_Chunk',
    'compute_vertex_subset_observation_chunk',
    'Ground_Observation_Density',
    'Ground_Observation_KDE_Density',
    'compute_ground_observation_density',
    'compute_ground_observation_kde_density',
    'Vertical_VP_Selection_Ground_Normal_Result',
    'solve_ground_normal_by_vertical_vp_selection',
    'Vanishing_Direction_Ground_Normal_Result',
    'solve_ground_normal_from_vanishing_directions',
    'Orthogonal_Consensus_Ground_Normal_Result',
    'solve_ground_normal_by_orthogonal_consensus',
    'solve_ground_normal_by_role_aware_orthogonal_consensus',
    'Person_Vertical_Direction_Evidence_Result',
    'fit_person_vertical_direction_evidence',
    'Equal_Weight_Vertical_Line_Ground_Normal_Result',
    'solve_ground_normal_by_equal_weight_vertical_lines',
    'Source_Weighted_Vertical_Line_Ground_Normal_Result',
    'solve_ground_normal_by_source_weighted_vertical_lines',
    'Person_Ankle_Foot_Shape',
    'Person_Ankle_Foot_Side',
    'Person_Ankle_Global_Config',
    'Person_Ankle_Height_Hypothesis',
    'Person_Ankle_Height_Shape',
    'Person_Ankle_Hypothesis_Segment',
    'Person_Ankle_Local_Cluster',
    'Person_Ankle_Local_Config',
    'Person_Ankle_Noise_Reason',
    'Person_Ankle_Observation_Table',
    'Person_Ankle_Plane_Config',
    'Person_Ankle_Plane_Input',
    'Person_Ankle_Plane_Result',
    'Person_Ankle_Plane_Status',
    'Person_Ankle_Recurrence_Episode',
    'Person_Ankle_Run',
    'Person_Ankle_Run_Provenance',
    'Person_Ankle_Source_Plane',
    'Person_Ankle_Space_Shape',
    'Person_Ankle_Time_Shape',
    'Person_Ankle_Transition_Check',
    'Person_Ankle_Transition_Config',
    'Person_Ankle_Transition_Outcome',
    'infer_person_ankle_plane_distribution',
]
